### ISSUE TITLE
 'NoneType' object has no attribute 'writeCsvFile'

### ISSUE THREAD

**Issue by Luluam** [BabylonJS/BlenderExporter#71]
I'm having this error for days trying to export a mesh from Blender to render in Babylon
Would anyone be able to help me understand the problem and overcome it?

```Python: Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\babylon_js\json_exporter.py", line 50, in execute
    if self.settings.writeCsvFile:
AttributeError: 'NoneType' object has no attribute 'writeCsvFile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\babylon_js\__init__.py", line 71, in execute
    exporter.execute(context, self.filepath, objects)
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\babylon_js\json_exporter.py", line 175, in execute
    if self.settings.writeCsvFile: stats_handler.close()
AttributeError: 'NoneType' object has no attribute 'writeCsvFile'
bpy.ops.export.bjs(filepath="C:\\Users\\lenovo\\Desktop\\globo3d1.babylon")
```

**Comment by Palmer-JC** [comment]
Exporter not yet working with Blender 4.0.  Try with 3.5 .  You can have
multiple versions installed at the same time
